// <auto-generated />
namespace _2CreateUser.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingTowns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingTowns));
        
        string IMigrationMetadata.Id
        {
            get { return "201611061206001_AddingTowns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
